### ISSUE TITLE
Keeping you busy - JSON problems. 

### ISSUE THREAD

**Issue by BKeyport** [sdetweil/MMM-Config#24]
Updated the JSON for my multi-month calendar module, attempting to add descriptions and so on. Restarted MagicMirror, loaded the config, page, and I get this. 

*** This is fatal, I had to reinstall mmm-config to get it back *** 

```
Entered content is not yet a valid JSON Form object.

The JSON Form library returned:
Error: The JSONForm contains an element whose type is unknown: "boolean"
    at formTree.buildFromLayout (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3368:11)
    at formTree. (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3442:29)
    at http://testbox:8080/modules/MMM-Config/node_modules/jsonform/deps/underscore.js:73:21
    at Function._.each._.forEach (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/deps/underscore.js:153:9)
    at formTree.buildFromLayout (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3438:7)
    at formTree. (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3442:29)
    at http://testbox:8080/modules/MMM-Config/node_modules/jsonform/deps/underscore.js:73:21
    at Function._.each._.forEach (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/deps/underscore.js:153:9)
    at formTree.buildFromLayout (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3438:7)
    at formTree. (http://testbox:8080/modules/MMM-Config/node_modules/jsonform/lib/jsonform.js:3442:29)
```

Here's my json. 

```
{
  "schema": {
    "MMM-Multimonth": {
      "type": "object",
      "title": "properties for MMM-Multimonth",
      "properties": {
        "module": {
          "type": "string",
          "title": "module",
          "default": "MMM-Multimonth",
          "readonly": true
        },
        "disabled": {
          "type": "boolean",
          "title": "disabled",
          "default": false
        },
        "position": {
          "type": "string",
          "title": "module position",
          "readonly": "true"
        },
        "classes": {
          "type": "string",
          "title": "classes",
          "default": ""
        },
        "order": {
          "type": "string",
          "title": "order",
          "default": "*"
        },
        "inconfig": {
          "type": "string",
          "title": "inconfig",
          "default": "0"
        },
        "index": {
          "type": "integer"
        },
        "config": {
          "type": "object",
          "title": "config",
          "properties": {
            "startMonth": {
              "type": "integer"
            },
            "monthCount": {
              "type": "integer"
            },
            "monthsVertical": {
              "type": "boolean"
            },
            "repeatWeekdaysVertical": {
              "type": "boolean"
            },
            "weekNumbers": {
              "type": "boolean"
            },
            "highlightWeekend": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "form": [
    {
      "key": "MMM-Multimonth.disabled",
      "htmlClass": "disabled_checkbox"
    },
    {
      "key": "MMM-Multimonth.position",
      "description": "use Module Positions section below to set or change"
    },
    {
      "key": "MMM-Multimonth.classes"
    },
    {
      "key": "MMM-Multimonth.order",
      "type": "hidden"
    },
    {
      "key": "MMM-Multimonth.inconfig",
      "type": "hidden"
    },
    {
      "key": "MMM-Multimonth.index",
      "type": "hidden"
    },
    {
      "type": "section",
      "title": "config",
      "items": [
        {
          "title": "startMonth",
          "key": "MMM-Multimonth.config.startMonth",
          "type": "number",
          "description": "Start of calendar in relation to current month, 0 being current"
        },
        {
          "title": "monthCount",
          "key": "MMM-Multimonth.config.monthCount",
          "type": "number",
          "description": "How many months do you want to display"
        },
        {
          "title": "monthsVertical",
          "key": "MMM-Multimonth.config.monthsVertical",
          "type": "boolean",
          "default": true,
          "description": "Display vertically"
        },
        {
          "title": "repeatWeekdaysVertical",
          "key": "MMM-Multimonth.config.repeatWeekdaysVertical",
          "type": "boolean",
          "default": false,
          "description": "Repeat Weekdays when vertical"
          
        },
        {
          "title": "weekNumbers",
          "key": "MMM-Multimonth.config.weekNumbers",
          "type": "boolean",
          "default": false,
          "description": "Show week numbers"
        },
        {
          "title": "highlightWeekend",
          "key": "MMM-Multimonth.config.highlightWeekend",
          "type": "boolean",
          "default": false,
          "description": "Highlight the weekends"
        }
      ]
    }
  ],
  "value": {
    "disabled": true,
    "module": "MMM-Multimonth",
    "position": "none",
    "order": "*",
    "inconfig": "0",
    "config": {
      "startMonth": -1,
      "monthCount": 3,
      "monthsVertical": true,
      "repeatWeekdaysVertical": false,
      "weekNumbers": false,
      "highlightWeekend": false
    }
  }
}

**Comment by sdetweil** [comment]
it will NEVER be fatal.. erase the schema.json from your module folder and restart MM.. 
it will regen the generic...

use the jsonform playground to test your form
https://jsonform.github.io/jsonform/playground/index.html

**Comment by sdetweil** [comment]
but...

three things
schema is data
1.   title is ONLY on the form, not in the schema (field names are the titles by default, unless specified in the form
form is presentation (can make data pretty) 
2.   data types are ONLY in the schema, not in the form (boolean,,,)
3.  value, must have the same shape as data
    so schema name must wrap all the values for the schema 
    
    
```
{
  "schema": {
    "MMM-Multimonth": {
      "type": "object",
      "title": "properties for MMM-Multimonth",
      "properties": {
        "module": {
          "type": "string",
          "title": "module",
          "default": "MMM-Multimonth",
          "readonly": true
        },
        "disabled": {
          "type": "boolean",
          "title": "disabled",
          "default": false
        },
        "position": {
          "type": "string",
          "title": "module position",
          "readonly": "true"
        },
        "classes": {
          "type": "string",
          "title": "classes",
          "default": ""
        },
        "order": {
          "type": "string",
          "title": "order",
          "default": "*"
        },
        "inconfig": {
          "type": "string",
          "title": "inconfig",
          "default": "0"
        },
        "index": {
          "type": "integer"
        },
        "config": {
          "type": "object",
          "title": "config",
          "properties": {
            "startMonth": {
              "type": "integer"
            },
            "monthCount": {
              "type": "integer"
            },
            "monthsVertical": {
              "type": "boolean"
            },
            "repeatWeekdaysVertical": {
              "type": "boolean"
            },
            "weekNumbers": {
              "type": "boolean"
            },
            "highlightWeekend": {
              "type": "boolean"
            }
          }
        }
      }
    }
  },
  "form": [
    {
      "key": "MMM-Multimonth.disabled",
      "htmlClass": "disabled_checkbox"
    },
    {
      "key": "MMM-Multimonth.position",
      "description": "use Module Positions section below to set or change"
    },
    {
      "key": "MMM-Multimonth.classes"
    },
    {
      "key": "MMM-Multimonth.order",
      "type": "hidden"
    },
    {
      "key": "MMM-Multimonth.inconfig",
      "type": "hidden"
    },
    {
      "key": "MMM-Multimonth.index",
      "type": "hidden"
    },
    {
      "type": "section",
      "title": "config",
      "items": [
        {
          "title": "startMonth",
          "key": "MMM-Multimonth.config.startMonth",
          "description": "Start of calendar in relation to current month, 0 being current"
        },
        {
          "title": "monthCount",
          "key": "MMM-Multimonth.config.monthCount",
          "description": "How many months do you want to display"
        },
        {
          "title": "monthsVertical",
          "key": "MMM-Multimonth.config.monthsVertical",
          "default": true,
          "description": "Display vertically"
        },
        {
          "title": "repeatWeekdaysVertical",
          "key": "MMM-Multimonth.config.repeatWeekdaysVertical",
          "default": false,
          "description": "Repeat Weekdays when vertical"
          
        },
        {
          "title": "weekNumbers",
          "key": "MMM-Multimonth.config.weekNumbers",
          "default": false,
          "description": "Show week numbers"
        },
        {
          "title": "highlightWeekend",
          "key": "MMM-Multimonth.config.highlightWeekend",
          "default": false,
          "description": "Highlight the weekends"
        }
      ]
    }
  ],
  "value": {
   "MMM-Multimonth": {
    "disabled": true,
    "module": "MMM-Multimonth",
    "position": "none",
    "order": "*",
    "inconfig": "0",
    "config": {
      "startMonth": -1,
      "monthCount": 3,
      "monthsVertical": true,
      "repeatWeekdaysVertical": false,
      "weekNumbers": false,
      "highlightWeekend": false
    }
   }
  }
}
```

**Comment by BKeyport** [comment]
OK - I've got a headache, and I'm totally lost here. 

The validator is reporting the data is good. 

Playground is reporting the error I show above. 

It visually looks to me like it's the same setup as I had on my other module, other than different field types.

**Comment by sdetweil** [comment]
the strategy on playground, is to delete one section at a time, value then form..  
fix the schema
add the form,  fix the form
add the value, fix the value

**Comment by sdetweil** [comment]
you had title: tags in the schema section , maybe not a problem

had boolean values in the form section
```
      {
          "title": "weekNumbers",
          "key": "MMM-Multimonth.config.weekNumbers",
          "type": "boolean",
          "default": false,
          "description": "Show week numbers"
        },
```
then in the value section 
the schema says 
   "MMM-Multi-month":{}

so the value section has to be that way too
```
    value: { 
      "MMM-Multi-month:{
           value key/data pairs
       }
     }
```

**Comment by BKeyport** [comment]
Got it, was confused with the multiple types.
