### ISSUE TITLE
EADDRINUSE: address already in use :::8200

### ISSUE THREAD

**Issue by jalibu** [sdetweil/MMM-Config#9]
**System**
- MacOS
- Chrome

**Steps to reproduce**
1. Start MagicMirror with "npm run server"
2. Open Browser at localhost:8080
3. Refresh Page in Browser

```
[24.05.2021 19:48.55.548] [ERROR] Whoops! There was an uncaught exception...
[24.05.2021 19:48.55.551] [ERROR] Error: listen EADDRINUSE: address already in use :::8200
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at Class.remote_start (/Users/me/git/MagicMirror/modules/MMM-Config/node_helper.js:961:12)
    at Class.startit (/Users/me/git/MagicMirror/modules/MMM-Config/node_helper.js:86:10)
    at Class.socketNotificationReceived (/Users/I543928/git/MagicMirror/modules/MMM-Config/node_helper.js:105:12)
    at Socket.<anonymous> (/Users/me/git/MagicMirror/js/node_helper.js:109:11)
    at Socket.emit (events.js:315:20)
    at Socket.emitUntyped (/Users/me/git/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /Users/I543928/git/MagicMirror/node_modules/socket.io/dist/socket.js:428:39 {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 8200
}
```

**Comment by khassel** [comment]
The port 8200 is used by the module and it seems you are running another app on this port.

@sdetweil is it possible to set the port in the config instead of using the fix port 8200?

**Comment by sdetweil** [comment]
working on it now

**Comment by khassel** [comment]
do not stress, there is no rush ...

**Comment by sdetweil** [comment]
fix pushed, now find free port, passes to config page

git pull 
npm install 

use the QR or 
http://mm_ip:mm_port/modules/MMM-Config/review

**Comment by sdetweil** [comment]
@khassel  I hate having users be forced to change config when we can discover things programmatically

**Comment by jalibu** [comment]
Solved!
